package main.pythonServiceClient;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2021-11-03T22:17:10.507+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://PythonService.main/", name = "PTServicePort")
@XmlSeeAlso({ObjectFactory.class})
public interface PTServicePort {

    @WebMethod
    @Action(input = "http://PythonService.main/PTServicePort/transRequest", output = "http://PythonService.main/PTServicePort/transResponse")
    @RequestWrapper(localName = "trans", targetNamespace = "http://PythonService.main/", className = "PythonServiceClient.Trans")
    @ResponseWrapper(localName = "transResponse", targetNamespace = "http://PythonService.main/", className = "PythonServiceClient.TransResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String trans();
}
