package main.pythonServiceClient;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-10-26T11:32:14.208+08:00
 * Generated source version: 3.4.4
 *
 */
@WebService(targetNamespace = "http://PythonService.main/", name = "PTServicePort")
@XmlSeeAlso({ObjectFactory.class})
public interface PTServicePort {

    @WebMethod
    @Action(input = "http://PythonService.main/PTServicePort/transRequest", output = "http://PythonService.main/PTServicePort/transResponse")
    @RequestWrapper(localName = "trans", targetNamespace = "http://PythonService.main/", className = "pythonServiceClient.Trans")
    @ResponseWrapper(localName = "transResponse", targetNamespace = "http://PythonService.main/", className = "pythonServiceClient.TransResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String trans()
;
}
