package main.DataServiceClient;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2021-11-09T16:57:16.312+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://DataService/", name = "DataServicePort")
@XmlSeeAlso({ObjectFactory.class})
public interface DataServicePort {

    @WebMethod
    @RequestWrapper(localName = "getAllData", targetNamespace = "http://DataService/", className = "DataServiceClient.GetAllData")
    @ResponseWrapper(localName = "getAllDataResponse", targetNamespace = "http://DataService/", className = "DataServiceClient.GetAllDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getAllData();
}
