package main.PTServiceClient;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2021-11-09T16:56:55.174+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://PythonService/", name = "PTServicePort")
@XmlSeeAlso({ObjectFactory.class})
public interface PTServicePort {

    @WebMethod
    @RequestWrapper(localName = "trans", targetNamespace = "http://PythonService/", className = "PTServiceClient.Trans")
    @ResponseWrapper(localName = "transResponse", targetNamespace = "http://PythonService/", className = "PTServiceClient.TransResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String trans();
}
